apiVersion: v1
kind: Service
metadata:
  name: druid-zookeeper
  namespace: druid
  labels:
    component: zookeeper
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    protocol: TCP
  - name: election
    port: 3888
    targetPort: 3888
    protocol: TCP
  - name: server
    port: 2888
    targetPort: 2888
    protocol: TCP
  selector:
    component: zookeeper
