apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: druid-middlemanager
  namespace: druid
  labels:
    component: middlemanager
spec:
  serviceName: druid-middlemanager
  replicas: 1
  selector:
    matchLabels:
      component: middlemanager
  template:
    metadata:
      labels:
        component: middlemanager
    spec:
      containers:
      - name: druid
        args: ["bin/run-druid", "middleManager", "/druid/conf"]
        image: deepaksood619/zendruid:2.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8091
          name: http
        - containerPort: 8100
          name: peon-0
        - containerPort: 8101
          name: peon-1
        - containerPort: 8102
          name: peon-2
        volumeMounts:
        - mountPath: /var/druid/
          name: data
#        livenessProbe:
#          initialDelaySeconds: 60
#          httpGet:
#            path: /status/health
#            port: 8091
        readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /status/health
            port: 8091
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "druid-pvc"